<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '公司介绍';
$typeArr[3] = '文化理念';
$typeArr[4] = '组织架构';
$typeArr[5] = '企业文化';
$typeArr[6] = '新闻中心';
$typeArr[7] = '活动公告';
$typeArr[8] = '公司新闻';
$typeArr[9] = '行业新闻';
$typeArr[10] = '产品中心';
$typeArr[11] = '电子数码';
$typeArr[12] = '音响设备';
$typeArr[13] = '音箱外设';
$typeArr[14] = '声卡设备';
$typeArr[15] = '其他设备';
$typeArr[16] = '人才招聘';
$typeArr[17] = '客户案例';
$typeArr[18] = '客户见证';
$typeArr[19] = '品牌客户';
$typeArr[20] = '客户评价';
$typeArr[21] = '售后服务';
$typeArr[22] = '联系我们';
?>