<?php
$z[0]=Array("field","",108,136);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",138,167);
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n                <li id=\"menu-item-2\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-2\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",226,469);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>