<?php
$z[0]=Array("global","",97,123);
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",182,206);
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",241,262);
$z[2][4]['name']="mobile";
$z[3]=Array("global","",279,297);
$z[3][4]['name']="fax";
$z[4]=Array("global","",317,334);
$z[4][4]['name']="qq";
$z[5]=Array("global","",356,376);
$z[5][4]['name']="eamil";
$z[6]=Array("global","",398,420);
$z[6][4]['name']="address";

?>