<?php
$z[0]=Array("global","",990,1016);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channelartlist","\r\n            <li id=\"menu-item-1\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-1\"> <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n              <ul class=\"sub-menu\">\r\n                {dede:channel type='son' noself='yes'}\r\n                <li id=\"menu-item-2\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-2\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                {/dede:channel}\r\n              </ul>\r\n            </li>\r\n            ",1625,2218);
$z[1][4]['typeid']="top";

?>