<?php
$z[0]=Array("arclist","\r\n        <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n        ",105,260);
$z[0][4]['typeid']="6";
$z[0][4]['row']="10";
$z[0][4]['titlelen']="50";
$z[1]=Array("global","",453,474);
$z[1][4]['name']="mobile";
$z[2]=Array("global","",503,521);
$z[2][4]['name']="fax";
$z[3]=Array("global","",548,565);
$z[3][4]['name']="qq";
$z[4]=Array("global","",596,616);
$z[4][4]['name']="eamil";
$z[5]=Array("global","",646,668);
$z[5][4]['name']="address";

?>