<?php
$z[0]=Array("field","",300,319);
$z[0][4]['name']="title";
$z[1]=Array("global","",320,346);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",387,416);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",456,514);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1222,1257);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1504,1533);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n        <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n          <div class=\"folio-thumb\">\r\n            <div class=\"mediaholder\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" class=\"thumb\"></div>\r\n            <div class=\"opacity-pic\"></div>\r\n          </div>\r\n          <h3>[field:title/]</h3>\r\n          </a></li>\r\n        ",1737,2112);
$z[6][4]['pagesize']="9";
$z[7]=Array("pagelist","",2250,2321);
$z[7][4]['listitem']="info,index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2394,2429);
$z[8][4]['filename']="left.htm";
$z[9]=Array("include","",2480,2517);
$z[9][4]['filename']="footer.htm";

?>